openapi: 3.0.0
info:
  title: Inditex
  description: Inditex API
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local server
  - url: https://api.inditex.com
    description: Production server
security:
  - ApiKeyAuth: [ ]
paths:
  /v1/prices:
    post:
      summary: Get price
      description: Get price
      operationId: getPrice
      tags:
        - price
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PriceRequest'
      responses:
        '200':
          description: Price
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PriceResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDefinition'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDefinition'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDefinition'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDefinition'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDefinition'
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: ApiKey
  schemas:
    PriceRequest:
      type: object
      properties:
        brandId:
          type: integer
          description: Brand identifier
          example: 1
        productId:
          type: integer
          description: Product identifier
          example: 35455
        date:
          type: string
          format: date-time
          description: Date
          example: 2020-06-14T10:00:00
      required:
        - brandId
        - productId
        - date
    PriceResponse:
      type: object
      properties:
        brandId:
          type: integer
          description: Brand identifier
          example: 1
        productId:
          type: integer
          description: Product identifier
          example: 35455
        startDate:
          type: string
          description: Start date
          example: 2020-06-14T00:00:00
        endDate:
          type: string
          description: End date
          example: 2020-12-31T23:59:59
        priceId:
          type: integer
          description: Price list
          example: 1
        price:
          type: number
          format: double
          description: Price
          example: 35.50
        currency:
          type: string
          description: Currency
          example: EUR
      required:
        - brandId
        - productId
        - price
        - currency
    ErrorDefinition:
      type: object
      properties:
        code:
          type: string
          description: Error code
          example: 0x0001
        message:
          type: string
          description: Error message
          example: Error message
      required:
        - code
        - message